### PR TITLE
Add local resources

### PR DESCRIPTION
**Pull request by slochower**

### CODE REVIEW

**Review by nhenriksen — APPROVED** [review]
/home is not 44 TB on Kirkwood.
/data is 37 TB on both Kirkwood/Onsager
All are Raid6

**Comment by slochower** [comment]
Whoops. Does this look correct now?

**Comment by slochower** [comment]
Worth putting in thunderbolt, lightning, shannon, etc...?

**Comment by nhenriksen** [comment]
nah ... they are all effectively personal machines now

**Comment by nhenriksen** [comment]
I suggest using lightning and thunderbolt as desktops for new people joing the lab going forward

**Pull request merged**
